name = "gramps"
version = "0.1.0"
description = "A Gleam WebSocket Datagram Library"

licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "gramps" }

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
