name = "gramps"
version = "1.1.0"
description = "A Gleam WebSocket Datagram Library"

licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "gramps" }

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_http = "~> 3.5"
gleam_crypto = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.0"
