name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: "27.0"
          gleam-version: "1.2.0"
          rebar3-version: "3"
          # elixir-version: "1.14.2"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
